name: Checksum Code
description: Checksum action via container image
inputs:
  # Checksum Code configuration
  prompt:
    description: "Instructions for Checksum. Can be a direct prompt or custom template."
    required: false
    default: ""
  settings:
    description: "Checksum Code settings as JSON string or path to settings JSON file"
    required: false
    default: ""

  # Auth configuration
  app_id:
    description: "Checksum App ID"
    required: true
  app_private_key:
    description: "Checksum App private key"
    required: true

runs:
  using: docker
  image: docker://ghcr.io/harsh-sset/checksum-code-priv:latest
branding:
  color: blue
  icon: check-circle
